name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze app source (lib/)
        run: flutter analyze lib/

      - name: Analyze app tests (test/)
        run: flutter analyze test/

      - name: Analyze custom lint rules (packages/my_app_lint/)
        run: dart analyze packages/my_app_lint/lib/

  unit-test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          channel: "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Run unit & widget tests
        run: flutter test

  integration-test:
    needs: analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          channel: "stable"

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y xvfb
          flutter pub get

      - name: Run integration tests
        run: xvfb-run flutter test integration_test/
